services:
  api:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      MODE: "development"
      SEARCH_API_URL: "http://search:80/expressions/large-search"
      EMBEDDING_API_URL: "http://embedding:80/embed"
      SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
