services:
  question-answering:
    build: .
    restart: no
    labels:
      - logging=true
    command: >
      uv run python -Xfrozen_modules=off -m debugpy 
      --listen 0.0.0.0:5678
      -m uvicorn web:app --host 0.0.0.0 --port 80 --proxy-headers --timeout-keep-alive 300 --workers 1 --reload --reload-dir /app
    ports:
      - "8000:80"
      - "5678:5678"
    volumes:
      - .:/app
      - ./config:/config
    environment:
      MODE: "development"
      SEARCH_API_URL: "http://search:80/expressions/search"
      LOG_SPARQL_ALL: "false"
      EMBEDDING_API_URL: "http://embedding:80/embed"
      MU_SPARQL_ENDPOINT: "http://database:8890/sparql"
      MU_SPARQL_TIMEOUT: "30"
      # to use ollama locally, you need to set the following environment variables:
      GENERATION_PROVIDER: "ollama"
      GENERATION_ENDPOINT: "http://ollama:11434"
      GENERATION_MODEL: "mistral-nemo"
      # to use the mistral model, you need to set the following environment variables:
      # GENERATION_PROVIDER: "mistralai"
      # GENERATION_MODEL: "mistral-medium-3-5"
      # GENERATION_API_KEY: ${GENERATION_API_KEY}
      GENERATION_TIMEOUT: "300.0"
      MAX_CONTENT_CHARS: "50000"
      REQUEST_TIMEOUT: "10.0"
      ALLOW_MU_AUTH_SUDO: "true"
    networks:
      - debug
      - default

networks:
  debug:
    external: true
