services:
  api:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      MODE: "development"
      SEARCH_API_URL: "http://search:80/expressions/large-search"
      EMBEDDING_API_URL: "http://embedding:80/embed"
      MU_SPARQL_ENDPOINT: "http://database:8890/sparql"
      MU_SPARQL_TIMEOUT: "30"
      GENERATION_ENDPOINT: "http://ollama:11434"
      GENERATION_MODEL: "mistral-nemo"
      MAX_CONTENT_CHARS: "1000"
      REQUEST_TIMEOUT: "10.0"
      GENERATION_TIMEOUT: "300.0"
      ALLOW_MU_AUTH_SUDO: "true"